name: Run Unittests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specify the required Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Download PostgreSQL
    - name: Download PostgreSQL
      run: |
        choco install postgresql -y
      shell: cmd

    # Step 5: Initialise db
    - name: Initialize PostgreSQL Database
      run: |
        set "PATH=C:\Program Files\PostgreSQL\17\bin;%PATH%"
        echo "PATH=C:\Program Files\PostgreSQL\17\bin;%PATH%" >> $GITHUB_ENV
        pg_ctl initdb -D C:\pgdata
        echo "Updating pg_hba.conf for trust authentication..."
        echo "local   all             all                                     trust" >> C:/pgdata/pg_hba.conf
        echo "host    all             all             127.0.0.1/32            trust" >> C:/pgdata/pg_hba.conf
        echo "host    all             all             ::1/128                 trust" >> C:/pgdata/pg_hba.conf
        echo "listen_addresses = '127.0.0.1'" >> C:/pgdata/postgresql.conf
        pg_ctl -D C:\pgdata -l logfile -o "-h 127.0.0.1" start
        psql -c "CREATE DATABASE postgres;" -U postgres
        psql -c "CREATE USER postgres WITH PASSWORD '12345';" -U postgres
      shell: cmd
      continue-on-error: true  # Ensures subsequent steps execute even if this fails

    - name: View PostgreSQL Logs
      if: always()  # Ensures this step runs regardless of success or failure of previous steps
      run: |
        echo "PostgreSQL Log File Contents:"
        type logfile
      shell: cmd

    # Step 6: Read all the .env variabes from test.env
    - name: Load test.env variables
      run: |
        python -c "from dotenv import load_dotenv; load_dotenv(dotenv_path='test.env')"
    
    # Step 7: Reset .env variabes that contain credentials
    - name: Set environment variables
      run: |
        echo PROJECT_PATH=${{ github.workspace }} >> $GITHUB_ENV
        echo PASSWORD="12345" >> $GITHUB_ENV

    # Step 8: Run unittest for all test folders
    - name: Run Backend unittests
      run: |
        python -m unittest discover -s tests/backend -p "*.py"
      continue-on-error: true

    - name: Run UI unittests
      run: |
        python -m unittest discover -s tests/ui -p "*.py"
      continue-on-error: true

    - name: Run Utils unittests
      run: |
        python -m unittest discover -s tests/utils -p "*.py"
      continue-on-error: true
        
        
